##
## EPITECH PROJECT, 2021
## ubuntu [Container ubuntu:latest (/hungry_bose)]
## File description:
## Makefile
##

CFLAGS = make -C

all:
	$(CFLAGS) ncurses
	$(CFLAGS) sfml

# tests_run:
# 	$(CFLAGS) solver tests_run
# 	$(CFLAGS) generator tests_run

clean:
	$(CFLAGS) ncurses clean
	$(CFLAGS) sfml clean

fclean:
	$(CFLAGS) ncurses fclean
	$(CFLAGS) sfml fclean

re:	fclean all

.PHONY: all fclean re