##
## EPITECH PROJECT, 2021
## ubuntu [Container ubuntu:latest (/hungry_bose)]
## File description:
## Makefile
##

all:
	make -C ncurses
	make -C sfml
	make -C sdl2

clean:
	make -C ncurses clean
	make -C sfml clean
	make -C sdl2 clean

fclean:
	make -C ncurses fclean
	make -C sfml fclean
	make -C sdl2 fclean

re:	fclean all

.PHONY: all fclean re