##
## EPITECH PROJECT, 2021
## B-OOP-400-BDX-4-1-arcade-alexandre.lacoste
## File description:
## Makefile
##

all:
		make -C pacman
		make -C nibbler

clean:
		make -C pacman clean
		make -C nibbler clean

fclean:
		make -C pacman fclean
		make -C nibbler fclean

re:		fclean all

.PHONY: all clean fclean re