##
## EPITECH PROJECT, 2021
## B-OOP-400-BDX-4-1-arcade-alexandre.lacoste
## File description:
## Makefile
##

CFLAGS 	= make -C

all:
		$(CFLAGS) pacman

clean:
		$(CFLAGS) pacman clean

fclean:
		$(CFLAGS) pacman fclean

re:		fclean all

.PHONY: all clean fclean re