##
## EPITECH PROJECT, 2021
## B-OOP-400-BDX-4-1-arcade-alexandre.lacoste
## File description:
## Makefile
##

all:
		make -C pacman

clean:
		make -C pacman clean

fclean:
		make -C pacman fclean

re:		fclean all

.PHONY: all clean fclean re